transacoes: 
  events: "sse-streams"
  duration: "2"

limites: 
  url: http://localhost:8086

transaction:
  url: http://localhost:8080

spring: 
  redis:     
    port: 6379
    host: localhost
    timeout: 5000
  kafka: 
    bootstrap-servers: localhost:9092
