#Esse arquivo é a fonte da verdade para as propriedades do sistema microservice. [ Git ops (maybe?) ]

transacoes: 
  events: "transferencias"
  duration: "3"

limites: 
  url: http://localhost:8086

transaction:
  url: http://localhost:8080

spring: 
  redis:     
    port: 6379
    host: localhost
    timeout: 5000
  kafka: 
    bootstrap-servers: localhost:9092
